language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository

before_install:
    - yes | sdkmanager "platforms;android-29"

script: ./gradlew testDebug
