# SPDX-FileCopyrightText: 2016-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2015-2024 Stefan Niedermann <info@niedermann.it>
# SPDX-FileCopyrightText: 2024 Andy Scherzinger <info@andy-scherzinger.de>
# SPDX-License-Identifier: GPL-3.0-or-later

# can be overridden by ~/.gradle/gradle.properties
NC_TEST_SERVER_BASEURL=http://10.0.2.2
NC_TEST_SERVER_USERNAME=test
NC_TEST_SERVER_PASSWORD=test

android.useAndroidX=true
org.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
org.gradle.dependency.verification.console=verbose
kotlin.daemon.jvmargs=-Xmx3072m -XX:+UseParallelGC
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
kapt.incremental.apt=true
org.gradle.daemon=true
org.gradle.configuration-cache=true
android.enableAppCompileTimeRClass=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false


# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
