name: "🚀 Feature request"
description: "Propose an idea for Notes Android"
labels: [ "enhancement" ]
body:

  - type: markdown
    attributes:
      value: |
        **Guidelines for submitting issues:**

        * Please search the existing issues first, it's likely that your issue was already reported or even fixed.
        * This repository is *only* for issues within the Notes Android app, **not** for the [Notes server app](https://github.com/nextcloud/notes/issues/) and **not** for the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when…
    validations:
      required: true

  - type: textarea
    id: preferred-solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.