# synced from @nextcloud/android-config
name: Auto approve sync
on:
  pull_request_target:
    branches:
      - master
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled

concurrency:
  group: sync-approve-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  auto-approve:
    name: Auto approve sync
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'sync') && github.actor == 'nextcloud-android-bot' }}
    steps:
      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
